#pragma checksum "..\..\..\UserControls\UcSucuk.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7D08B69C0FD8F6761139F26A26CAD55DA0C6E6F4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OZBESIN.UserControls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OZBESIN.UserControls
{


    /// <summary>
    /// UcSucuk
    /// </summary>
    public partial class UcSucuk : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector
    {

#line default
#line hidden

        private bool _contentLoaded;

        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent()
        {
            if (_contentLoaded)
            {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OZBESIN;component/usercontrols/ucsucuk.xaml", System.UriKind.Relative);

#line 1 "..\..\..\UserControls\UcSucuk.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);

#line default
#line hidden
        }

        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target)
        {
            switch (connectionId)
            {
                case 1:
                    this.gridSucuk = ((System.Windows.Controls.Grid)(target));
                    return;
                case 2:
                    this.GridPrint = ((System.Windows.Controls.Grid)(target));
                    return;
                case 3:
                    this.flow = ((System.Windows.Documents.FlowDocument)(target));
                    return;
                case 4:
                    this.PrintImage = ((System.Windows.Controls.Image)(target));

#line 169 "..\..\..\UserControls\UcSucuk.xaml"
                    this.PrintImage.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Image_MouseDown);

#line default
#line hidden
                    return;
            }
            this._contentLoaded = true;
        }
    }
}

