#pragma checksum "..\..\..\Forms\Uruns.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D262C329E5D9869CB62E91BE55BB00D3D19B403A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MahApps.Metro.Controls;
using OZBESIN_KAYIT.Forms;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OZBESIN_KAYIT.Forms {
    
    
    /// <summary>
    /// Uruns
    /// </summary>
    public partial class Uruns : MahApps.Metro.Controls.MetroWindow, System.Windows.Markup.IComponentConnector {
        
        
        #line 38 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Aramatxt;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid katgrid;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Olcubrmtxt;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Stoktxt;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox KDVtxt;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox Durumtxt;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UrunIDtxt;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox KategoriIDtxt;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Barkodtxt;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox KategoriIDcmb;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UrunAdtxt;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UrunFiyattxt;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UrunIndirimsiztxt;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UrunResimtxt;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UrunIceriktxt;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\Forms\Uruns.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datagrd;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OZBESIN_KAYIT;component/forms/uruns.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Forms\Uruns.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 11 "..\..\..\Forms\Uruns.xaml"
            ((OZBESIN_KAYIT.Forms.Uruns)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 20 "..\..\..\Forms\Uruns.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Kaydetbtn_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 21 "..\..\..\Forms\Uruns.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Silbtn_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 22 "..\..\..\Forms\Uruns.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Yenibtn_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 23 "..\..\..\Forms\Uruns.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Excel_Aktar_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.Aramatxt = ((System.Windows.Controls.TextBox)(target));
            
            #line 38 "..\..\..\Forms\Uruns.xaml"
            this.Aramatxt.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.Aramatxt_TextChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.katgrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 8:
            this.Olcubrmtxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.Stoktxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.KDVtxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.Durumtxt = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.UrunIDtxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.KategoriIDtxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.Barkodtxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.KategoriIDcmb = ((System.Windows.Controls.ComboBox)(target));
            
            #line 65 "..\..\..\Forms\Uruns.xaml"
            this.KategoriIDcmb.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.KategoriIDcmb_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 16:
            
            #line 66 "..\..\..\Forms\Uruns.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.UrunAdtxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.UrunFiyattxt = ((System.Windows.Controls.TextBox)(target));
            
            #line 69 "..\..\..\Forms\Uruns.xaml"
            this.UrunFiyattxt.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.UrunFiyattxt_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 19:
            this.UrunIndirimsiztxt = ((System.Windows.Controls.TextBox)(target));
            
            #line 71 "..\..\..\Forms\Uruns.xaml"
            this.UrunIndirimsiztxt.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.UrunIndirimsiztxt_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 20:
            this.UrunResimtxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.UrunIceriktxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.img = ((System.Windows.Controls.Image)(target));
            return;
            case 23:
            this.datagrd = ((System.Windows.Controls.DataGrid)(target));
            
            #line 88 "..\..\..\Forms\Uruns.xaml"
            this.datagrd.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.listKategori_SelectionChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

